<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-CU78B49A" failures="0" tests="3" name="com.akbr.testngpractice.Timeout_program" time="0.268" errors="1" timestamp="2020-06-13T00:21:18 IST" skipped="0">
  <testcase classname="com.akbr.testngpractice.Timeout_program" name="testcase1" time="0.243">
    <error message="Method com.akbr.testngpractice.Timeout_program.testcase1() didn&#039;t finish within the time-out 200" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.akbr.testngpractice.Timeout_program.testcase1() didn't finish within the time-out 200
at java.base@12.0.2/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1031)
at java.base@12.0.2/java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1541)
at java.base@12.0.2/java.lang.invoke.MethodType$ConcurrentWeakInternSet.add(MethodType.java:1380)
at java.base@12.0.2/java.lang.invoke.MethodType.makeImpl(MethodType.java:327)
at java.base@12.0.2/java.lang.invoke.MethodHandleNatives.findMethodHandleType(MethodHandleNatives.java:377)
at java.base@12.0.2/java.util.concurrent.FutureTask.setException(FutureTask.java:247)
at java.base@12.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:269)
at java.base@12.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@12.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base@12.0.2/java.lang.Thread.run(Thread.java:835)
]]>
    </error>
  </testcase> <!-- testcase1 -->
  <testcase classname="com.akbr.testngpractice.Timeout_program" name="testcaes2" time="0.022"/>
  <testcase classname="com.akbr.testngpractice.Timeout_program" name="testcase3" time="0.003"/>
</testsuite> <!-- com.akbr.testngpractice.Timeout_program -->
